name: Setup CI
on:
  repository_dispatch:
    types: [setup]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: upptime/uptime-monitor@master
        with:
          command: "setup"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
